version: '3.8'
services:
  person-db:
    container_name: 'Person-knowledge-db'
    image: postgres:16.0
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '1111:5432'
    volumes:
      - person-k:/var/lib/postgresql/data
    networks:
      - network-p
volumes:
  person-k:
    name: 'person-knowledge'
networks:
  network-p:
    name: person-knowledge-network
    driver: bridge