spring:
  application:
    name: knowledge
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:1111/person-knowledge-db
    username: person
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
app:
  security:
    token_prefix: "Bearer "
    secret_key: "BANANOUUUAINDANAOCOMEUBANANOUUUAINDANAOCOMEUJACOMEU00000JACOMEU11111"
    expiration_date: 100000000