spring:
  application:
    name: knowledge
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING.DATABASE.URL}
    username: ${SPRING.DATABASE.USERNAME}
    password: ${SPRING.DATABASE.PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host:
    port:
    username:
    password:

app:
  security:
    token_prefix: ${APP.SECURITY.TOKEN.PREFIX}
    secret_key: ${APP.SECURITY.SECRET.KEY}
    expiration_date: ${APP.SECURITY.EXPIRATION.DATE}
